SEARCH_URL = "https://api.company-information.service.gov.uk/advanced-search/companies"
LIMIT = 10 #move to config?
RATE = 5 #move to config?
LOG_FORMAT = "%(asctime)s - %(levelname)s - %(message)s" #TO-DO: show function / more context here
LOG_FILE_NAME = "leadTracker.log"
LOG_FOLDER = "Logs"
TIMEZONE = "UTC"
SHEET_SCHEMA_PATH = "SHEET_SCHEMA.yaml"
CACHE_DB = "cache.db"